<script src="<?= __VENDOR; ?>datatables.net/jquery.dataTables.js"></script>
<script src="<?= __VENDOR; ?>datatables.net-bs4/dataTables.bootstrap4.js"></script>
<script src="<?= __VENDOR; ?>datatables.net-scroller/dataTables.scroller.js"></script>
<script src="<?= __VENDOR; ?>datatables.net-responsive/dataTables.responsive.js"></script>
<script src="<?= __VENDOR; ?>datatables.net-responsive-bs4/responsive.bootstrap4.js"></script>
<script src="<?= __VENDOR; ?>datatables.net-buttons/dataTables.buttons.js"></script>
<script src="<?= __VENDOR; ?>datatables.net-buttons/buttons.html5.js"></script>
<script src="<?= __VENDOR; ?>datatables.net-buttons/buttons.print.js"></script>
<script src="<?= __VENDOR; ?>datatables.net-buttons/buttons.colVis.js"></script>
<script src="<?= __VENDOR; ?>datatables.net-buttons/jszip.min.js"></script>
<script src="<?= __VENDOR; ?>datatables.net-buttons/pdfmake.min.js"></script>
<script src="<?= __VENDOR; ?>datatables.net-buttons/vfs_fonts.js"></script>
<script src="<?= __VENDOR; ?>datatables.net-buttons-bs4/buttons.bootstrap4.js"></script>
